_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: a519920a-14ca-49c4-bb29-fd8cf92acae1
name: 'Andy Yulianto'
mail: admin@example.com
slogan: 'Sebuah catatan dari seorang hamba'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
